## library() calls go here
library(conflicted)
library(dotenv)
library(targets)
library(tarchetypes)
library(ICIKendallTau)
suppressPackageStartupMessages(library(ComplexHeatmap))
suppressPackageStartupMessages(library(SummarizedExperiment))
options(tflow.report_dir = "docs")
paint::mask_print()


## library() calls go here
library(visualizationQualityControl)
library(dplyr)
library(tidyr)
library(furrr)
library(rlang)
library(patchwork)
library(ggplot2)
library(ggforce)
library(scales)
library(latex2exp)
#library(magick)
options(parallelly.fork.enable = TRUE, future.rng.onMisuse = "ignore")
future::plan(multicore, workers = 3)
theme_set(cowplot::theme_cowplot())
paint::mask_print()
tar_option_set(memory = "transient")
options(tflow.report_dir = "docs")
