# packages we use ------
library(conflicted)
library(dotenv)
library(targets)
library(tarchetypes)
library(ICIKendallTau)
library(documentNumbering)
suppressPackageStartupMessages(library(ComplexHeatmap))
suppressPackageStartupMessages(library(SummarizedExperiment))

library(visualizationQualityControl)
library(dplyr)
library(tidyr)
library(furrr)
library(rlang)
library(patchwork)
library(ggplot2)
library(ggforce)
library(scales)
library(latex2exp)
library(limma)
library(crew)
library(rmarkdown)
library(flextable)

# options we set ------
# options(parallelly.fork.enable = TRUE, future.rng.onMisuse = "ignore")
# future::plan(multicore, workers = 3)
theme_set(cowplot::theme_cowplot())
tar_option_set(memory = "transient")
options(tflow.report_dir = "docs")
paint::mask_print()
