Rscript python/run_multi.R 1
Rscript python/run_multi.R 2
Rscript python/run_multi.R 3
Rscript python/run_multi.R 4
Rscript python/run_multi.R 5
Rscript python/run_multi.R 6
Rscript python/run_multi.R 7
Rscript python/run_multi.R 8
Rscript python/run_multi.R 9
Rscript python/run_multi.R 10
Rscript python/run_multi.R 11
Rscript python/run_multi.R 12
