Rscript run_multi.R 1
Rscript run_multi.R 2
Rscript run_multi.R 3
Rscript run_multi.R 4
Rscript run_multi.R 5
Rscript run_multi.R 6
Rscript run_multi.R 7
Rscript run_multi.R 8
Rscript run_multi.R 9
Rscript run_multi.R 10
Rscript run_multi.R 11
Rscript run_multi.R 12
